"""Enforces API documentation discipline: every production route must wrap its
success payload in ApiResponse[...].

This is checked through ``app.openapi()`` — FastAPI's own, version-stable view
of the API — rather than by walking ``app.routes``. The internal route tree
changed across versions (fastapi 0.138 wraps every included router in a
``_IncludedRouter`` with no flat ``.routes``; starlette nests sub-routers), so a
hand-rolled route walk would silently find nothing and pass *vacuously*. The
``_MIN_EXPECTED_PATHS`` floor below turns any such regression into a loud
failure instead.

Re-used by every later CRUD ticket — extend the allowances sparingly.
"""
from __future__ import annotations

from app.main import app

# The schema is generated by FastAPI itself, so it cannot under-count because of
# a route-tree change — but this floor still guards against the whole API
# silently disappearing (e.g. an import-time failure) and the check passing with
# zero routes. Keep it comfortably below the real count (~95 documented paths).
_MIN_EXPECTED_PATHS = 60

_METHODS = {"get", "post", "put", "patch", "delete"}


def _success_schema_ref(operation: dict) -> str | None:
    """Return the component name referenced by an operation's 2xx JSON response.

    Scans every 2xx (and ``default``) status code so routes that answer with a
    non-200 success (e.g. ``202 Accepted`` on the async import endpoints) are
    still inspected. Returns ``None`` when no 2xx response carries a JSON schema.
    """
    for code, resp in operation.get("responses", {}).items():
        if not (code == "default" or code.startswith("2")):
            continue
        schema = resp.get("content", {}).get("application/json", {}).get("schema", {})
        ref = schema.get("$ref")
        if ref:
            return ref.split("/")[-1]
    return None


def test_every_route_uses_api_response() -> None:
    paths = app.openapi()["paths"]

    assert len(paths) >= _MIN_EXPECTED_PATHS, (
        f"only {len(paths)} documented paths found (expected >= "
        f"{_MIN_EXPECTED_PATHS}); route discovery looks broken — refusing to let "
        "this discipline check pass vacuously"
    )

    offenders: list[str] = []
    for path, operations in paths.items():
        for method, operation in operations.items():
            if method not in _METHODS:
                continue
            ref = _success_schema_ref(operation)
            if ref is None:
                offenders.append(f"{method.upper()} {path}: no 2xx JSON response schema")
            elif not ref.startswith("ApiResponse"):
                offenders.append(
                    f"{method.upper()} {path}: success schema is {ref}, "
                    "not ApiResponse[...]"
                )

    assert not offenders, (
        "routes missing the ApiResponse[...] envelope:\n" + "\n".join(offenders)
    )
